version: "2"
services:
  httpd:
    build: .
    links:
      - maria_db:db
    ports:
      - 8888:80
    volumes:
      - ./app:/var/www/html
  maria_db:
    container_name: mariadb
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8081:3306

volumes:
  data: