version: "2"
services:
  httpd:
    build: .
    links:
      - maria_db:db
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
  maria_db:
    container_name: mariadb
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8082:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    links:
      - maria_db:db
    ports:
      - "8081:80"
    volumes:
      - /sessions

volumes:
  data: